apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: app-prod
  labels:
    app: product
    env: app-prod
    access: private
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: dt-pod-port
  selector:
    app: product
    env: app-prod
    access: private
