apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: app-prod
  labels:
    app: product
    env: app-prod
    access: private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      env: app-prod
      access: private
  template:
    metadata:
      labels:
        app: product
        env: app-prod
        access: private
    spec:
      containers:
        - name: product
          image: CONTAINER_IMAGE
          command:
            - "/go/bin/product"
            - "--port"
            - "8080"
          ports:
            - name: dt-pod-port
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "1024Mi"
            limits:
              cpu: "250m"
              memory: "1024Mi"
          imagePullPolicy: Always
      imagePullSecrets:
        - name: "regcred"
