// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: mobile_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMobileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile *Mobile `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
}

func (x *CreateMobileRequest) Reset() {
	*x = CreateMobileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mobile_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMobileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMobileRequest) ProtoMessage() {}

func (x *CreateMobileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMobileRequest.ProtoReflect.Descriptor instead.
func (*CreateMobileRequest) Descriptor() ([]byte, []int) {
	return file_mobile_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMobileRequest) GetMobile() *Mobile {
	if x != nil {
		return x.Mobile
	}
	return nil
}

type CreateMobileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateMobileResponse) Reset() {
	*x = CreateMobileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mobile_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMobileResponse) ProtoMessage() {}

func (x *CreateMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mobile_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMobileResponse.ProtoReflect.Descriptor instead.
func (*CreateMobileResponse) Descriptor() ([]byte, []int) {
	return file_mobile_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMobileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_mobile_service_proto protoreflect.FileDescriptor

var file_mobile_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x14, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x32, 0x71, 0x0a, 0x0d, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x60, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f,
	0x62, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x3a, 0x01, 0x2a, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2d, 0x47,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mobile_service_proto_rawDescOnce sync.Once
	file_mobile_service_proto_rawDescData = file_mobile_service_proto_rawDesc
)

func file_mobile_service_proto_rawDescGZIP() []byte {
	file_mobile_service_proto_rawDescOnce.Do(func() {
		file_mobile_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_mobile_service_proto_rawDescData)
	})
	return file_mobile_service_proto_rawDescData
}

var file_mobile_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mobile_service_proto_goTypes = []interface{}{
	(*CreateMobileRequest)(nil),  // 0: pb.CreateMobileRequest
	(*CreateMobileResponse)(nil), // 1: pb.CreateMobileResponse
	(*Mobile)(nil),               // 2: pb.Mobile
}
var file_mobile_service_proto_depIdxs = []int32{
	2, // 0: pb.CreateMobileRequest.mobile:type_name -> pb.Mobile
	0, // 1: pb.MobileService.CreateMobile:input_type -> pb.CreateMobileRequest
	1, // 2: pb.MobileService.CreateMobile:output_type -> pb.CreateMobileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mobile_service_proto_init() }
func file_mobile_service_proto_init() {
	if File_mobile_service_proto != nil {
		return
	}
	file_mobile_message_proto_init()
	file_google_api_annotations_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mobile_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMobileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mobile_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMobileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mobile_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mobile_service_proto_goTypes,
		DependencyIndexes: file_mobile_service_proto_depIdxs,
		MessageInfos:      file_mobile_service_proto_msgTypes,
	}.Build()
	File_mobile_service_proto = out.File
	file_mobile_service_proto_rawDesc = nil
	file_mobile_service_proto_goTypes = nil
	file_mobile_service_proto_depIdxs = nil
}
